name: j5pos
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.10.0
  google_fonts: ^3.0.1
  get: 4.6.5
  hive: ^2.2.3
  intl: ^0.17.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/icon/
    - assets/img/
  uses-material-design: true

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon/j5posicon.png'
